#!/usr/bin/env bun
// scripts/sync-product-refs.ts
//
// Writes two reference files into each registered product's code folder:
//   - `.claude/HAMZAISH.md`   — factory coordination (committed in the product repo)
//   - `START-HERE.local.md`   — session orientation (gitignored, never committed)
// Idempotent — safe to re-run. Skips slot_reserved / killed products.
//
// START-HERE.local.md is a per-product "read me first" for any Claude Code
// session: critical do-not-break rules + pointers to the live source of truth.
// Its critical-rules section comes from `products/<slug>/rules.local.md`
// (gitignored here in the factory), so product secrets never reach this PUBLIC
// repo. Free-form notes belong in the product's own `CLAUDE.local.md`.
//
// Code locations are resolved from `code-paths.local.json` (git-ignored,
// machine-specific — copy `code-paths.example.json` and fill in your paths).
// No symlinks are committed to the repo.
//
// Usage:
//   bun scripts/sync-product-refs.ts             # write/refresh refs
//   bun scripts/sync-product-refs.ts --dry-run   # show what would change
//   bun scripts/sync-product-refs.ts --clean     # remove generated files (un-install)

import { readdir, readFile, writeFile, mkdir, unlink } from "node:fs/promises";
import { join, dirname, resolve } from "node:path";
import { existsSync } from "node:fs";

// Repo root = parent of this script's directory. Portable — no hardcoded path.
const HAMZAISH_ROOT = resolve(import.meta.dir, "..");
const DRY = process.argv.includes("--dry-run");
const CLEAN = process.argv.includes("--clean");
// --only <slug> limits the run to a single product (handy for a first/test run).
const ONLY = (() => {
  const i = process.argv.indexOf("--only");
  return i >= 0 ? (process.argv[i + 1] ?? null) : null;
})();

type ProductConfig = {
  slug: string;
  name: string;
  one_liner: string;
  stage: string;
  status: string;
  code_path: string | null;
  aliases?: string[];
};

async function loadCodePaths(): Promise<Record<string, string>> {
  const p = join(HAMZAISH_ROOT, "code-paths.local.json");
  if (!existsSync(p)) {
    console.warn(
      "⚠ code-paths.local.json not found — copy code-paths.example.json to it and fill in your local code paths. Nothing to sync.",
    );
    return {};
  }
  try {
    return JSON.parse(await readFile(p, "utf8"));
  } catch (e) {
    console.warn("⚠ code-paths.local.json is not valid JSON:", e);
    return {};
  }
}

function refContent(cfg: ProductConfig, codeAbsPath: string): string {
  return `# Hamzaish coordination

This product is registered in the **Hamzaish startup factory** at \`${HAMZAISH_ROOT}\`.

- **slug**: \`${cfg.slug}\`
- **name**: ${cfg.name}
- **stage**: \`${cfg.stage}\`
- **status**: \`${cfg.status}\`
- **factory entry**: \`${HAMZAISH_ROOT}/products/${cfg.slug}/\` (manifest, scope, status, decisions, learnings)
- **code (local)**: this directory — mapped from \`code-paths.local.json\` (never committed)

## Global slash commands available from anywhere

| Command | What it does |
|---|---|
| \`/hamzaish\` | Momentum router. Default = **just build** (→ \`/full-cycle\` or \`/auto\`). Opt into strategy rails or resume a stage when you want them. |
| \`/work-on ${cfg.slug}\` | Enter the canonical workspace flow — load config, scope, status, decisions, learnings, stage playbook, this product's CLAUDE.md. |
| \`/portfolio-pulse [hours]\` | All products snapshot — Top 3, on-fire, don't-touch. Tunes to time budget. |
| \`/brain-ask "<query>"\` | Query Hamzaish's brain across all products + learnings + playbooks. Add \`--product ${cfg.slug}\` to scope here. |
| \`/brain-ingest\` | Refresh the brain index after writes. |

## Hamzaish discipline (light touch — applies here too)

- **Read the product's own \`CLAUDE.md\` first** (this folder).
- **\`scope.md\`** — what this does AND what it deliberately doesn't.
- **Append-only \`decisions/\` log** for non-trivial choices: date · decision · why · what would prove it wrong · revisit trigger.
- **\`learnings.md\`** — capture the *transferable* lesson (what worked / what bit us / the fix). Never put keys, credentials, or proprietary internals here.
- **Measurement framework before launch** — north star, activation criterion, retention targets, false-positive shape.
- **Security review before any user touches it** — auth/session, data exposure, input validation, dependency CVEs.
- **Don't modify another product's code from this product's session.**

## Where Hamzaish remembers things about this product

- Scope: \`${HAMZAISH_ROOT}/products/${cfg.slug}/scope.md\`
- Decisions: \`${HAMZAISH_ROOT}/products/${cfg.slug}/decisions/\`
- Status (live): \`${HAMZAISH_ROOT}/products/${cfg.slug}/status.md\`
- Learnings: \`${HAMZAISH_ROOT}/products/${cfg.slug}/learnings.md\`
- Cross-product learnings that reference this product: query with \`bun ${HAMZAISH_ROOT}/brain/ask.ts --product ${cfg.slug} "<query>"\`

## Regenerating this file

This file is auto-generated by \`${HAMZAISH_ROOT}/scripts/sync-product-refs.ts\`. Edits will be overwritten on next sync. Tweak the script if you need a structural change.
`;
}

function startHereContent(
  cfg: ProductConfig,
  criticalRules: string | null,
): string {
  const factory = `${HAMZAISH_ROOT}/products/${cfg.slug}`;
  // Strip HTML comments so notes-to-self in rules.local.md don't leak into output.
  const cleanedRules = (criticalRules ?? "").replace(/<!--[\s\S]*?-->/g, "").trim();
  const rulesBlock = cleanedRules
    ? cleanedRules
    : `_No product-specific hard rules recorded yet._ Add them to \`${factory}/rules.local.md\` (gitignored in the factory) and re-run \`bun run sync-refs\`.`;

  return `# START HERE — ${cfg.name}

> **Local-only — never committed.** This file is gitignored (\`*.local.md\`), so it
> never reaches the repo and can't leak if this product goes public. It is
> **auto-generated** by Hamzaish — edits are overwritten on the next
> \`bun run sync-refs\`. Put free-form personal notes in \`CLAUDE.local.md\` instead.

Read this whenever you (re)open this repo or resume an older session, so you act
on current state and don't break something that's easy to break here.

## ⚠️ Critical rules (read first)

${rulesBlock}

## What this is

**${cfg.name}** — ${cfg.one_liner}

Stage \`${cfg.stage}\` · status \`${cfg.status}\` · slug \`${cfg.slug}\`

## How to work here

- **Read the product's own \`CLAUDE.md\`** (this folder) for conventions; then
  \`AGENTS.md\` and \`.claude/rules/\` if present.
- **Before committing**, run the project's checks (typecheck / lint / tests /
  build — see \`CLAUDE.md\` or \`package.json\`). Never start a test *watcher* in a
  one-shot session — use the run-once form.
- **Commit small and logical**; don't push to \`main\` if a branch/PR is expected.

## Where the live state lives (single source of truth — read, don't duplicate)

- **Status (live):** \`${factory}/status.md\`
- **Scope (in / out):** \`${factory}/scope.md\`
- **Decisions log:** \`${factory}/decisions/\`
- **Learnings:** \`${factory}/learnings.md\`
- Run \`/work-on ${cfg.slug}\` to load all of the above at once.

## Running long / autonomously

- For a measurable objective, use \`/goal "<objective>"\` — it loops, scores
  against a rubric, and **resumes across sessions** from \`.goal/<name>/\`.
- For unattended multi-session runs, see \`${HAMZAISH_ROOT}/docs/autonomy.md\`.

---
_Auto-generated by \`${HAMZAISH_ROOT}/scripts/sync-product-refs.ts\`. The critical-rules section is sourced from \`${factory}/rules.local.md\` (gitignored)._
`;
}

/**
 * Make sure the product repo ignores the local-only files we (and /goal) drop
 * into it, so the global auto-commit hook can never stage them. Additive and
 * safe — appending a pattern never untracks an already-tracked file. Returns the
 * patterns it added (empty if nothing changed).
 */
async function ensureIgnored(
  codeAbs: string,
  patterns: string[],
): Promise<string[]> {
  const giPath = join(codeAbs, ".gitignore");
  const current = existsSync(giPath) ? await readFile(giPath, "utf8") : "";
  const present = new Set(current.split(/\r?\n/).map((l) => l.trim()));
  const missing = patterns.filter((p) => !present.has(p));
  if (missing.length === 0 || DRY) return missing;
  const sep = current === "" || current.endsWith("\n") ? "" : "\n";
  const block = `${sep}\n# Local-only Claude context & autonomy artifacts (managed by sync-product-refs)\n${missing.join("\n")}\n`;
  await writeFile(giPath, current + block, "utf8");
  return missing;
}

async function main() {
  const productsDir = join(HAMZAISH_ROOT, "products");
  const codePaths = await loadCodePaths();
  const entries = await readdir(productsDir, { withFileTypes: true });
  const productSlugs = entries
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name);

  let written = 0,
    skipped = 0,
    removed = 0;
  for (const slug of productSlugs) {
    if (ONLY && slug !== ONLY) continue;
    const cfgPath = join(productsDir, slug, "product.config.json");
    if (!existsSync(cfgPath)) {
      console.log(`  · ${slug}: no product.config.json, skip`);
      skipped++;
      continue;
    }
    const cfg = JSON.parse(await readFile(cfgPath, "utf8")) as ProductConfig;
    if (cfg.status === "slot_reserved" || cfg.status === "killed") {
      console.log(`  · ${slug}: status=${cfg.status}, skip`);
      skipped++;
      continue;
    }

    // Resolve the code location from the local map (fallback: config.code_path).
    const codeAbs = codePaths[slug] || cfg.code_path || "";
    if (!codeAbs) {
      console.log(`  · ${slug}: no entry in code-paths.local.json, skip`);
      skipped++;
      continue;
    }
    if (!existsSync(codeAbs)) {
      console.log(`  · ${slug}: code path ${codeAbs} doesn't exist, skip`);
      skipped++;
      continue;
    }

    // Guarantee the product repo ignores the local-only files before we write
    // any, so an auto-commit hook can never stage START-HERE.local.md / .goal/.
    if (!CLEAN) {
      const added = await ensureIgnored(codeAbs, ["*.local.md", ".goal/"]);
      if (added.length) {
        console.log(
          `  ${DRY ? "→ would add to" : "✎"} .gitignore (${slug}): ${added.join(", ")}`,
        );
      }
    }

    // Optional gitignored critical-rules source (never committed to this public
    // factory). Embedded verbatim into the product's START-HERE.local.md.
    const rulesPath = join(productsDir, slug, "rules.local.md");
    const criticalRules = existsSync(rulesPath)
      ? await readFile(rulesPath, "utf8")
      : null;

    const artifacts = [
      {
        path: join(codeAbs, ".claude", "HAMZAISH.md"),
        content: refContent(cfg, codeAbs),
        label: "HAMZAISH.md",
      },
      {
        path: join(codeAbs, "START-HERE.local.md"),
        content: startHereContent(cfg, criticalRules),
        label: "START-HERE.local.md",
      },
    ];

    for (const art of artifacts) {
      if (CLEAN) {
        if (existsSync(art.path)) {
          if (DRY) {
            console.log(`  − would remove ${art.path}`);
          } else {
            await unlink(art.path);
            console.log(`  − removed ${art.path}`);
          }
          removed++;
        }
        continue;
      }

      if (DRY) {
        console.log(
          `  → would write ${art.path} (${art.content.length} chars)`,
        );
        written++;
        continue;
      }

      await mkdir(dirname(art.path), { recursive: true });
      let existing = "";
      if (existsSync(art.path)) {
        existing = await readFile(art.path, "utf8");
      }
      if (existing === art.content) {
        console.log(`  · ${slug}: ${art.label} unchanged`);
        skipped++;
        continue;
      }
      await writeFile(art.path, art.content, "utf8");
      console.log(`  + ${slug} → ${art.path}`);
      written++;
    }
  }

  console.log(
    `\nDone. written=${written} skipped=${skipped} removed=${removed}${DRY ? " (dry-run)" : ""}`,
  );
}

main().catch((e) => {
  console.error("× sync failed:", e);
  process.exit(1);
});
