#!/usr/bin/env bun
// scripts/sync-product-refs.ts
//
// Writes a `.claude/HAMZAISH.md` reference file into each registered product's code folder.
// Idempotent — safe to re-run. Skips slot_reserved products with no real code.
//
// Usage:
//   bun scripts/sync-product-refs.ts             # write/refresh refs
//   bun scripts/sync-product-refs.ts --dry-run   # show what would change
//   bun scripts/sync-product-refs.ts --clean     # remove HAMZAISH.md files (un-install)

import { readdir, readFile, writeFile, mkdir, unlink } from "node:fs/promises";
import { join, dirname } from "node:path";
import { existsSync, lstatSync } from "node:fs";

const HAMZAISH_ROOT = "/Users/hamza/Claude/Hamzaish";
const DRY = process.argv.includes("--dry-run");
const CLEAN = process.argv.includes("--clean");

type ProductConfig = {
  slug: string;
  name: string;
  one_liner: string;
  stage: string;
  status: string;
  code_path: string;
  aliases?: string[];
};

function refContent(cfg: ProductConfig, codeAbsPath: string): string {
  return `# Hamzaish coordination

This product is registered in the **Hamzaish startup factory** at \`${HAMZAISH_ROOT}\`.

- **slug**: \`${cfg.slug}\`
- **name**: ${cfg.name}
- **stage**: \`${cfg.stage}\`
- **status**: \`${cfg.status}\`
- **factory entry**: \`${HAMZAISH_ROOT}/products/${cfg.slug}/\` (manifest, status, decisions, launch assets)
- **code symlink**: \`${HAMZAISH_ROOT}/products/${cfg.slug}-code\` → this directory

## Global slash commands available from anywhere

| Command | What it does |
|---|---|
| \`/work-on ${cfg.slug}\` | Enter the canonical workspace flow — load config, status, decisions, stage playbook, this product's CLAUDE.md, surface open threads. |
| \`/portfolio-pulse [hours]\` | All products snapshot — Top 3, on-fire, don't-touch. Tunes to time budget. |
| \`/brain-ask "<query>"\` | Query Hamzaish's brain across all products + learnings + playbooks. Add \`--product ${cfg.slug}\` to scope here. |
| \`/brain-ingest\` | Refresh the brain index after writes. |
| \`/hamzaish\` (alias of \`/full-cycle\`) | setup → spec → plan → test → build → review → ship with approval gates. |

## Hamzaish discipline (light touch — applies here too)

- **Read the product's own \`CLAUDE.md\` first** (this folder).
- **\`scope.md\`** — what this does AND what it deliberately doesn't.
- **Append-only \`decisions/\` log** for non-trivial choices: date · decision · why · what would prove it wrong · revisit trigger.
- **Measurement framework before launch** — north star, activation criterion, retention targets, false-positive shape.
- **Security review before any user touches it** — auth/session, data exposure, input validation, dependency CVEs.
- **Don't modify another product's code from this product's session.**

## Where Hamzaish remembers things about this product

- Decisions: \`${HAMZAISH_ROOT}/products/${cfg.slug}/decisions/\`
- Status (live): \`${HAMZAISH_ROOT}/products/${cfg.slug}/status.md\`
- Launch assets (when applicable): \`${HAMZAISH_ROOT}/products/${cfg.slug}/launch/\`
- Cross-product learnings that reference this product: query with \`bun ${HAMZAISH_ROOT}/brain/ask.ts --product ${cfg.slug} "<query>"\`

## Regenerating this file

This file is auto-generated by \`${HAMZAISH_ROOT}/scripts/sync-product-refs.ts\`. Edits will be overwritten on next sync. Tweak the script if you need a structural change.
`;
}

async function main() {
  const productsDir = join(HAMZAISH_ROOT, "products");
  const entries = await readdir(productsDir, { withFileTypes: true });
  const productSlugs = entries
    .filter((e) => e.isDirectory() && !e.name.startsWith("_") && !e.name.endsWith("-code"))
    .map((e) => e.name);

  let written = 0, skipped = 0, removed = 0;
  for (const slug of productSlugs) {
    const cfgPath = join(productsDir, slug, "product.config.json");
    if (!existsSync(cfgPath)) {
      console.log(`  · ${slug}: no product.config.json, skip`);
      skipped++;
      continue;
    }
    const cfg = JSON.parse(await readFile(cfgPath, "utf8")) as ProductConfig;
    if (cfg.status === "slot_reserved" || cfg.status === "killed") {
      console.log(`  · ${slug}: status=${cfg.status}, skip`);
      skipped++;
      continue;
    }

    // Resolve the code symlink to get the absolute code path
    const codeLink = join(productsDir, `${slug}-code`);
    if (!existsSync(codeLink)) {
      console.log(`  · ${slug}: symlink ${slug}-code missing, skip`);
      skipped++;
      continue;
    }
    let codeAbs: string;
    try {
      codeAbs = lstatSync(codeLink).isSymbolicLink()
        ? await Bun.file(codeLink).name || codeLink
        : codeLink;
    } catch {
      codeAbs = codeLink;
    }
    // Use a more reliable readlink
    const real = await Bun.$`readlink ${codeLink}`.text();
    codeAbs = real.trim() || codeLink;

    if (!existsSync(codeAbs)) {
      console.log(`  · ${slug}: code path ${codeAbs} doesn't exist, skip`);
      skipped++;
      continue;
    }

    const refPath = join(codeAbs, ".claude", "HAMZAISH.md");

    if (CLEAN) {
      if (existsSync(refPath)) {
        if (DRY) {
          console.log(`  − would remove ${refPath}`);
        } else {
          await unlink(refPath);
          console.log(`  − removed ${refPath}`);
        }
        removed++;
      }
      continue;
    }

    const content = refContent(cfg, codeAbs);

    if (DRY) {
      console.log(`  → would write ${refPath} (${content.length} chars)`);
      written++;
      continue;
    }

    await mkdir(dirname(refPath), { recursive: true });
    // Only rewrite if content changed
    let existing = "";
    if (existsSync(refPath)) {
      existing = await readFile(refPath, "utf8");
    }
    if (existing === content) {
      console.log(`  · ${slug}: HAMZAISH.md unchanged`);
      skipped++;
      continue;
    }
    await writeFile(refPath, content, "utf8");
    console.log(`  + ${slug} → ${refPath}`);
    written++;
  }

  console.log(`\nDone. written=${written} skipped=${skipped} removed=${removed}${DRY ? " (dry-run)" : ""}`);
}

main().catch((e) => {
  console.error("× sync failed:", e);
  process.exit(1);
});
