#!/usr/bin/env bun
// scripts/sync-product-refs.ts
//
// Writes a `.claude/HAMZAISH.md` reference file into each registered product's code folder.
// Idempotent — safe to re-run. Skips slot_reserved / killed products.
//
// Code locations are resolved from `code-paths.local.json` (git-ignored,
// machine-specific — copy `code-paths.example.json` and fill in your paths).
// No symlinks are committed to the repo.
//
// Usage:
//   bun scripts/sync-product-refs.ts             # write/refresh refs
//   bun scripts/sync-product-refs.ts --dry-run   # show what would change
//   bun scripts/sync-product-refs.ts --clean     # remove HAMZAISH.md files (un-install)

import { readdir, readFile, writeFile, mkdir, unlink } from "node:fs/promises";
import { join, dirname, resolve } from "node:path";
import { existsSync } from "node:fs";

// Repo root = parent of this script's directory. Portable — no hardcoded path.
const HAMZAISH_ROOT = resolve(import.meta.dir, "..");
const DRY = process.argv.includes("--dry-run");
const CLEAN = process.argv.includes("--clean");

type ProductConfig = {
  slug: string;
  name: string;
  one_liner: string;
  stage: string;
  status: string;
  code_path: string | null;
  aliases?: string[];
};

async function loadCodePaths(): Promise<Record<string, string>> {
  const p = join(HAMZAISH_ROOT, "code-paths.local.json");
  if (!existsSync(p)) {
    console.warn(
      "⚠ code-paths.local.json not found — copy code-paths.example.json to it and fill in your local code paths. Nothing to sync.",
    );
    return {};
  }
  try {
    return JSON.parse(await readFile(p, "utf8"));
  } catch (e) {
    console.warn("⚠ code-paths.local.json is not valid JSON:", e);
    return {};
  }
}

function refContent(cfg: ProductConfig, codeAbsPath: string): string {
  return `# Hamzaish coordination

This product is registered in the **Hamzaish startup factory** at \`${HAMZAISH_ROOT}\`.

- **slug**: \`${cfg.slug}\`
- **name**: ${cfg.name}
- **stage**: \`${cfg.stage}\`
- **status**: \`${cfg.status}\`
- **factory entry**: \`${HAMZAISH_ROOT}/products/${cfg.slug}/\` (manifest, scope, status, decisions, learnings)
- **code (local)**: this directory — mapped from \`code-paths.local.json\` (never committed)

## Global slash commands available from anywhere

| Command | What it does |
|---|---|
| \`/hamzaish\` | Momentum router. Default = **just build** (→ \`/full-cycle\` or \`/auto\`). Opt into strategy rails or resume a stage when you want them. |
| \`/work-on ${cfg.slug}\` | Enter the canonical workspace flow — load config, scope, status, decisions, learnings, stage playbook, this product's CLAUDE.md. |
| \`/portfolio-pulse [hours]\` | All products snapshot — Top 3, on-fire, don't-touch. Tunes to time budget. |
| \`/brain-ask "<query>"\` | Query Hamzaish's brain across all products + learnings + playbooks. Add \`--product ${cfg.slug}\` to scope here. |
| \`/brain-ingest\` | Refresh the brain index after writes. |

## Hamzaish discipline (light touch — applies here too)

- **Read the product's own \`CLAUDE.md\` first** (this folder).
- **\`scope.md\`** — what this does AND what it deliberately doesn't.
- **Append-only \`decisions/\` log** for non-trivial choices: date · decision · why · what would prove it wrong · revisit trigger.
- **\`learnings.md\`** — capture the *transferable* lesson (what worked / what bit us / the fix). Never put keys, credentials, or proprietary internals here.
- **Measurement framework before launch** — north star, activation criterion, retention targets, false-positive shape.
- **Security review before any user touches it** — auth/session, data exposure, input validation, dependency CVEs.
- **Don't modify another product's code from this product's session.**

## Where Hamzaish remembers things about this product

- Scope: \`${HAMZAISH_ROOT}/products/${cfg.slug}/scope.md\`
- Decisions: \`${HAMZAISH_ROOT}/products/${cfg.slug}/decisions/\`
- Status (live): \`${HAMZAISH_ROOT}/products/${cfg.slug}/status.md\`
- Learnings: \`${HAMZAISH_ROOT}/products/${cfg.slug}/learnings.md\`
- Cross-product learnings that reference this product: query with \`bun ${HAMZAISH_ROOT}/brain/ask.ts --product ${cfg.slug} "<query>"\`

## Regenerating this file

This file is auto-generated by \`${HAMZAISH_ROOT}/scripts/sync-product-refs.ts\`. Edits will be overwritten on next sync. Tweak the script if you need a structural change.
`;
}

async function main() {
  const productsDir = join(HAMZAISH_ROOT, "products");
  const codePaths = await loadCodePaths();
  const entries = await readdir(productsDir, { withFileTypes: true });
  const productSlugs = entries
    .filter((e) => e.isDirectory() && !e.name.startsWith("_"))
    .map((e) => e.name);

  let written = 0,
    skipped = 0,
    removed = 0;
  for (const slug of productSlugs) {
    const cfgPath = join(productsDir, slug, "product.config.json");
    if (!existsSync(cfgPath)) {
      console.log(`  · ${slug}: no product.config.json, skip`);
      skipped++;
      continue;
    }
    const cfg = JSON.parse(await readFile(cfgPath, "utf8")) as ProductConfig;
    if (cfg.status === "slot_reserved" || cfg.status === "killed") {
      console.log(`  · ${slug}: status=${cfg.status}, skip`);
      skipped++;
      continue;
    }

    // Resolve the code location from the local map (fallback: config.code_path).
    const codeAbs = codePaths[slug] || cfg.code_path || "";
    if (!codeAbs) {
      console.log(`  · ${slug}: no entry in code-paths.local.json, skip`);
      skipped++;
      continue;
    }
    if (!existsSync(codeAbs)) {
      console.log(`  · ${slug}: code path ${codeAbs} doesn't exist, skip`);
      skipped++;
      continue;
    }

    const refPath = join(codeAbs, ".claude", "HAMZAISH.md");

    if (CLEAN) {
      if (existsSync(refPath)) {
        if (DRY) {
          console.log(`  − would remove ${refPath}`);
        } else {
          await unlink(refPath);
          console.log(`  − removed ${refPath}`);
        }
        removed++;
      }
      continue;
    }

    const content = refContent(cfg, codeAbs);

    if (DRY) {
      console.log(`  → would write ${refPath} (${content.length} chars)`);
      written++;
      continue;
    }

    await mkdir(dirname(refPath), { recursive: true });
    let existing = "";
    if (existsSync(refPath)) {
      existing = await readFile(refPath, "utf8");
    }
    if (existing === content) {
      console.log(`  · ${slug}: HAMZAISH.md unchanged`);
      skipped++;
      continue;
    }
    await writeFile(refPath, content, "utf8");
    console.log(`  + ${slug} → ${refPath}`);
    written++;
  }

  console.log(
    `\nDone. written=${written} skipped=${skipped} removed=${removed}${DRY ? " (dry-run)" : ""}`,
  );
}

main().catch((e) => {
  console.error("× sync failed:", e);
  process.exit(1);
});
